server:
    port: 8090
spring:
  application:
    name: bikemis
  datasource:
    url: jdbc:mysql://172.16.111.230:3306/bikemis?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: WULIkanwuli9@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
